### ISSUE TITLE
All entities lock.* are gone in v4.0.8

### ISSUE THREAD

**Issue by WildeRNS** [azerty9971/xtend_tuya#414]
After update to latest (v4.0.8) release all lock enteties are gone. rolled back to 0.7 revert all it back.

**Comment by moshebs1** [comment]
same here

**Comment by anhhthnhy** [comment]
For me, only Operate lock entity is disabled

**Comment by mercur1al** [comment]
My lock has become a camera

**Comment by Bloodiss** [comment]
same

**Comment by teymur1988** [comment]
same here. Lock entity is gone. Camera entity appeared.

**Comment by azerty9971** [comment]
Whooops, sorry about that everyone :'(.

Could each one of you post here the device diagnostic of your lock?

I'll try to add them quickly back.

And for those that became a camera, are the stream feeds working?

Sorry for the inconvenience :/.

Have a nice day,
Azerty

**Comment by mercur1al** [comment]
> Whooops, sorry about that everyone :'(.
> 
> Could each one of you post here the device diagnostic of your lock?
> 
> I'll try to add them quickly back.
> 
> And for those that became a camera, are the stream feeds working?
> 
> Sorry for the inconvenience :/.
> 
> Have a nice day, Azerty

The camera doesn't work, it's just not available. one more question, I have a problem with the lock, periodically it does not work in HA, could it be a problem that I am in Russia? Are there any solutions? for example, the IP addresses of the servers, so that I can add them to the workaround.

"DC:23:51:E8:C5:8A": {
"address": "DC:23:51:E8:C5:8A",
"uuid": "f3ca66459676b0e1",
"local_key": "Y<='-yjptPtbuF$j",
"device_id": "bfafeds3ofu6gweq",
"category": "jtmspro",
"product_id": "hc7n0urm",
"device_name": "A1 Ultra-JM",
"product_model": "AT1",
"product_name": "Smart lock"

**Comment by Bloodiss** [comment]
> Whooops, sorry about that everyone :'(.
> 
> Could each one of you post here the device diagnostic of your lock?
> 
> I'll try to add them quickly back.
> 
> And for those that became a camera, are the stream feeds working?
> 
> Sorry for the inconvenience :/.
> 
> Have a nice day, Azerty

Attach
[lock.json](https://github.com/user-attachments/files/21300412/lock.json)

**Comment by WildeRNS** [comment]
> Whooops, sorry about that everyone :'(.
> 
> Could each one of you post here the device diagnostic of your lock?
> 
> I'll try to add them quickly back.
> 
> And for those that became a camera, are the stream feeds working?
> 
> Sorry for the inconvenience :/.
> 
> Have a nice day, Azerty

[xtend_tuya-01JM4ZM8F8JF3BC5H96MTKJWN2-door-e8226fb8807ebf57c7ec0328167279ca.json](https://github.com/user-attachments/files/21300422/xtend_tuya-01JM4ZM8F8JF3BC5H96MTKJWN2-door-e8226fb8807ebf57c7ec0328167279ca.json)
[xtend_tuya-01JM4ZM8F8JF3BC5H96MTKJWN2-Deadbolt lock-b6ce9c9fa8c5086f64728d0ac4d6903f.json](https://github.com/user-attachments/files/21300423/xtend_tuya-01JM4ZM8F8JF3BC5H96MTKJWN2-Deadbolt.lock-b6ce9c9fa8c5086f64728d0ac4d6903f.json)
[xtend_tuya-01JM4ZM8F8JF3BC5H96MTKJWN2-LEOCK_N01牛头锁-badc1a49181f571630b81369953fe55d.json](https://github.com/user-attachments/files/21300424/xtend_tuya-01JM4ZM8F8JF3BC5H96MTKJWN2-LEOCK_N01.-badc1a49181f571630b81369953fe55d.json)
[xtend_tuya-01JM4ZM8F8JF3BC5H96MTKJWN2-Front door-6d0aa18b4567669ec1a61ff014559e58.json](https://github.com/user-attachments/files/21300425/xtend_tuya-01JM4ZM8F8JF3BC5H96MTKJWN2-Front.door-6d0aa18b4567669ec1a61ff014559e58.json)

**Comment by azerty9971** [comment]
Hello,
The latest release should fix this, can you update and let me know if everything is back to normal?

Sorry for the inconvenience,
Azerty

**Comment by mercur1al** [comment]
> Hello, The latest release should fix this, can you update and let me know if everything is back to normal?
> 
> Sorry for the inconvenience, Azerty

the lock appeared, but I still can't control it (most likely because I'm in Russia and the server is blocked. Do you have a list of server IP addresses? I'll add them to the bypass.

**Comment by azerty9971** [comment]
> > Hello, The latest release should fix this, can you update and let me know if everything is back to normal?
> > Sorry for the inconvenience, Azerty
> 
> the lock appeared, but I still can't control it (most likely because I'm in Russia and the server is blocked. Do you have a list of server IP addresses? I'll add them to the bypass.

All communication is going through the Tuya APIs, so if you can see device updates then there shouldn't be any IP blacklisting involved :/

Do you see anything in the system logs? (settings -> system -> logs)

**Comment by WildeRNS** [comment]
> Hello, The latest release should fix this, can you update and let me know if everything is back to normal?
> 
> Sorry for the inconvenience, Azerty

Will update tomorrow and write you back, thanks!

**Comment by teymur1988** [comment]
Update 4.0.9 brought back the lock. Thank you.  Operating the lock from HA, physically opens the lock but in HA it stays in the state below even after the lock is auto-locked. My lock when unlocked, automatically locks itself after a few seconds. This isn't reflected on the lock entity status.

<img width="601" height="594" alt="Image" src="https://github.com/user-attachments/assets/8f115309-2865-42a4-bcb6-d2c1ba640250" />

The Camera entity remained among the accessories, even though my lock doesn't have one.

<img width="323" height="507" alt="Image" src="https://github.com/user-attachments/assets/d0ace506-40fc-4ec5-8224-d039ed0b06a8" />

This is the lock I have:

<img width="345" height="595" alt="Image" src="https://github.com/user-attachments/assets/9a3ed1c1-17ac-4ebb-baa5-df615d5e76a3" />

**Comment by WildeRNS** [comment]
> Hello, The latest release should fix this, can you update and let me know if everything is back to normal?
> 
> Sorry for the inconvenience, Azerty

updated to latest version - lock working. thanks again!
