### ISSUE TITLE
xtend_tuya fails to load on Home Assistant 2025.12.0b0 – blocking import + unexpected keyword argument open_instruction_value

### ISSUE THREAD

**Issue by cloudbr34k84** [azerty9971/xtend_tuya#607]
### **Environment**

```text
Home Assistant OS: Yes  
Core: 2025.12.0b0  
Supervisor: 2025.11.6  
Operating System: 16.3  
Frontend: 20251126.0  

Integration: xtend_tuya (custom component)  
```

---

### **Summary of the Issue**

After upgrading to **Home Assistant 2025.12.0b0**, the `xtend_tuya` integration fails to load.

Two issues occur:

1. **Blocking call inside event loop (`import_module`)**
2. **Cover platform crashes due to invalid argument:**
   `TypeError: XTCoverEntityDescription.__init__() got an unexpected keyword argument 'open_instruction_value'`

This prevents the entire xtend_tuya entry from setting up.

---

#### **1. Blocking import inside event loop**

```
Detected blocking call to import_module with args ('custom_components.xtend_tuya.cover',)
inside the event loop by custom integration 'xtend_tuya'

Offending line:
custom_components/xtend_tuya/__init__.py:112
await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
```

#### **2. Import failure when loading cover platform**

```
Unexpected exception importing platform custom_components.xtend_tuya.cover

TypeError: XTCoverEntityDescription.__init__() got an unexpected keyword argument 'open_instruction_value'
```

#### **3. Resulting failure to set up entry**

```
ImportError: Exception importing custom_components.xtend_tuya.cover
Error setting up entry cloudxxx@gmail.com for xtend_tuya
```

---

### **Steps to Reproduce**

1. Upgrade Home Assistant to **2025.12.0b0**
2. Restart Home Assistant
3. `xtend_tuya` fails during setup with the above errors

---

### **Expected Behaviour**

* `xtend_tuya` loads without blocking the event loop
* Cover entities initialise without errors
* `XTCoverEntityDescription` accepts all expected parameters

---

### **Actual Behaviour**

* Import blocking is detected and logged as an error
* Cover platform fails to load due to incompatible init arguments
* Full xtend_tuya integration setup aborts

---

**Comment by ColtonYYZ** [comment]
I'm having the same issue...  here are my logs:

```
2025-11-26 22:36:06.323 WARNING (SyncWorker_20) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566140, 'tid': '34ae854acb4211f08372b2138f4eef91'}
2025-11-26 22:36:06.323 WARNING (SyncWorker_20) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566288, 'tid': '34c47a3ccb4211f095f1b62c9ee88591'}
2025-11-26 22:36:06.332 WARNING (SyncWorker_10) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566158, 'tid': '34afb7abcb4211f08d0c56ddd92d6dbf'}
2025-11-26 22:36:06.332 WARNING (SyncWorker_10) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566292, 'tid': '34c76abacb4211f095f1b62c9ee88591'}
2025-11-26 22:36:06.343 WARNING (SyncWorker_12) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566142, 'tid': '34b017f1cb4211f08372b2138f4eef91'}
2025-11-26 22:36:06.343 WARNING (SyncWorker_12) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566306, 'tid': '34c84497cb4211f0acfd76b8e2586027'}
2025-11-26 22:36:06.472 WARNING (SyncWorker_18) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566297, 'tid': '34c847a7cb4211f0a209ea7c08cf018d'}
2025-11-26 22:36:06.472 WARNING (SyncWorker_18) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566432, 'tid': '34dd9764cb4211f0be6a8e0252ddd80d'}
2025-11-26 22:36:06.484 WARNING (SyncWorker_5) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566294, 'tid': '34c5f44ccb4211f0a581967ee1c63c89'}
2025-11-26 22:36:06.484 WARNING (SyncWorker_5) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566448, 'tid': '34de96edcb4211f0a209ea7c08cf018d'}
2025-11-26 22:36:06.825 WARNING (SyncWorker_30) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566663, 'tid': '3500c08dcb4211f0a581967ee1c63c89'}
2025-11-26 22:36:06.825 WARNING (SyncWorker_30) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566789, 'tid': '35141a6dcb4211f09bb6b20636c5bbcd'}
2025-11-26 22:36:06.841 WARNING (SyncWorker_33) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566677, 'tid': '350220fbcb4211f0bc4d5668bfc77048'}
2025-11-26 22:36:06.841 WARNING (SyncWorker_33) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566806, 'tid': '3515be24cb4211f0acfd76b8e2586027'}
2025-11-26 22:36:06.842 WARNING (SyncWorker_13) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566672, 'tid': '3500fbd1cb4211f0be6a8e0252ddd80d'}
2025-11-26 22:36:06.842 WARNING (SyncWorker_13) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566805, 'tid': '3515d0c2cb4211f08d0c56ddd92d6dbf'}
2025-11-26 22:36:06.952 WARNING (SyncWorker_31) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566685, 'tid': '3502c8e7cb4211f0be6a8e0252ddd80d'}
2025-11-26 22:36:06.952 WARNING (SyncWorker_31) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214566915, 'tid': '3517ccc5cb4211f08d0c56ddd92d6dbf'}
2025-11-26 22:36:07.307 WARNING (SyncWorker_27) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214567126, 'tid': '354887dacb4211f0be6a8e0252ddd80d'}
2025-11-26 22:36:07.307 WARNING (SyncWorker_27) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214567263, 'tid': '355b81accb4211f095f1b62c9ee88591'}
2025-11-26 22:36:07.342 WARNING (SyncWorker_12) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214567133, 'tid': '3547ceb6cb4211f0be6a8e0252ddd80d'}
2025-11-26 22:36:07.342 WARNING (SyncWorker_12) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214567303, 'tid': '355ff97acb4211f08a9e8253b24e91cb'}
2025-11-26 22:36:08.748 ERROR (MainThread) [homeassistant.components.automation] Platform automation does not generate unique IDs. ID select_music_and_play_device already exists - ignoring automation.play_music_on_selected_player
2025-11-26 22:36:09.285 WARNING (SyncWorker_17) [custom_components.xtend_tuya] Response1: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214569118, 'tid': '36765744cb4211f0acfd76b8e2586027'}
2025-11-26 22:36:09.286 WARNING (SyncWorker_17) [custom_components.xtend_tuya] Response2: {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1764214569248, 'tid': '368b3e3acb4211f08a9e8253b24e91cb'}
2025-11-26 22:36:11.268 ERROR (ImportExecutor_0) [homeassistant.loader] Unexpected exception importing platform custom_components.xtend_tuya.cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1269, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1301, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/cover.py", line 109, in <module>
    XTCoverEntityDescription(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        key=XTDPCode.MACH_OPERATE,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        control_back_mode=XTDPCode.CONTROL_BACK_MODE,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
TypeError: XTCoverEntityDescription.__init__() got an unexpected keyword argument 'open_instruction_value'
2025-11-26 22:36:11.297 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.xtend_tuya.cover',) inside the event loop by custom integration 'xtend_tuya' at custom_components/xtend_tuya/__init__.py, line 112: await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1301: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/azerty9971/xtend_tuya/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 906, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 672, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/xtend_tuya/__init__.py", line 112, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

2025-11-26 22:36:11.299 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.xtend_tuya.cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1269, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1301, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/cover.py", line 109, in <module>
    XTCoverEntityDescription(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        key=XTDPCode.MACH_OPERATE,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        control_back_mode=XTDPCode.CONTROL_BACK_MODE,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
TypeError: XTCoverEntityDescription.__init__() got an unexpected keyword argument 'open_instruction_value'
2025-11-26 22:36:11.300 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry [redacted] for xtend_tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1269, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1301, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/cover.py", line 109, in <module>
    XTCoverEntityDescription(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        key=XTDPCode.MACH_OPERATE,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        control_back_mode=XTDPCode.CONTROL_BACK_MODE,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
TypeError: XTCoverEntityDescription.__init__() got an unexpected keyword argument 'open_instruction_value'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/__init__.py", line 112, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2589, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1182, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1182, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1182, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  [Previous line repeated 17 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1170, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1095, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1289, in _load_platform
    raise ImportError(
        f"Exception importing {self.pkg_path}.{platform_name}"
    ) from err
ImportError: Exception importing custom_components.xtend_tuya.cover
```

**Comment by Bloodiss** [comment]
same after update HA

**Comment by philspain72** [comment]
same

**Comment by scooper1** [comment]
+1

**Comment by azerty9971** [comment]
Hello all,
Can you retry using v4.2.6-beta.1?

Hopefully it should be compatible with HA2025.12+ :).

Recommended procedure: update XT, then before rebooting update HA to 2025.12.
This way the integration's version change would happen at the same time as the HA update and you shouldn't have any issue.

And since there have been a ton of changes on the regular Tuya's side, except some bugs in this version (I'll be watching closely and will try to fix them ASAP to restore full functionality).

Have a nice day,
Azerty

**Comment by kunickig** [comment]
I tried to do as you wrote but the problem still occurs with version  v4.2.6-beta.1 as well

**Comment by azerty9971** [comment]
can you put here the errors that you see in your system log?

Without this it's very hard for me to figure out what is happening...

Have a nice day,
Azerty

**Comment by kunickig** [comment]
Rejestrator: tuya_sharing
Źródło: /usr/local/lib/python3.13/site-packages/tuya_sharing/manager.py:138
Pierwsze zdarzenie: 12:08:59 (4 wystąpienia)
Ostatnio zalogowany: 12:09:10
on message error = 102


Rejestrator: tuya_sharing
Źródło: /usr/local/lib/python3.13/site-packages/tuya_sharing/manager.py:138
Pierwsze zdarzenie: 12:11:38 (324 wystąpienia)
Ostatnio zalogowany: 12:22:43

on message error = DeviceListener.update_device() takes 3 positional arguments but 4 were given

**Comment by Bloodiss** [comment]
`Error setting up entry Cloud Tuya for xtend_tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1269, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1301, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/cover.py", line 109, in <module>
    XTCoverEntityDescription(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        key=XTDPCode.MACH_OPERATE,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        control_back_mode=XTDPCode.CONTROL_BACK_MODE,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
TypeError: XTCoverEntityDescription.__init__() got an unexpected keyword argument 'open_instruction_value'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/__init__.py", line 114, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2589, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1182, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1170, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1095, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1289, in _load_platform
    raise ImportError(
        f"Exception importing {self.pkg_path}.{platform_name}"
    ) from err
ImportError: Exception importing custom_components.xtend_tuya.cover`
`Unexpected exception importing platform custom_components.xtend_tuya.cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1269, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1301, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/cover.py", line 109, in <module>
    XTCoverEntityDescription(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        key=XTDPCode.MACH_OPERATE,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        control_back_mode=XTDPCode.CONTROL_BACK_MODE,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
TypeError: XTCoverEntityDescription.__init__() got an unexpected keyword argument 'open_instruction_value' `
` Detected blocking call to import_module with args ('custom_components.xtend_tuya.cover',) inside the event loop by custom integration 'xtend_tuya' at custom_components/xtend_tuya/__init__.py, line 114: await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1301: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/azerty9971/xtend_tuya/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 906, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 672, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/config/custom_components/xtend_tuya/__init__.py", line 114, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)`
`Error while setting up xtend_tuya platform for switch: TuyaSwitchEntity.__init__() missing 1 required positional argument: 'dpcode_wrapper'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/xtend_tuya/switch.py", line 529, in async_setup_entry
    async_discover_device([*hass_data.manager.device_map])
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/switch.py", line 506, in async_discover_device
    entities.extend(
    ~~~~~~~~~~~~~~~^
        XTSwitchEntity.get_entity_instance(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        )
        ^
    )
    ^
  File "/config/custom_components/xtend_tuya/switch.py", line 507, in <genexpr>
    XTSwitchEntity.get_entity_instance(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        description, device, hass_data.manager
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/xtend_tuya/switch.py", line 619, in get_entity_instance
    return XTSwitchEntity(
        device, device_manager, XTSwitchEntityDescription(**description.__dict__)
    )
  File "/config/custom_components/xtend_tuya/switch.py", line 549, in __init__
    super(XTEntity, self).__init__(device, device_manager, description)  # type: ignore
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TuyaSwitchEntity.__init__() missing 1 required positional argument: 'dpcode_wrapper' `

**Comment by azerty9971** [comment]
can you try with 4.2.6-beta.2 and let me know if you still have the issue?

Have a nice day,
Azerty

**Comment by antonio1475** [comment]
> can you try with 4.2.6-beta.2 and let me know if you still have the issue?
> 
> Have a nice day, Azerty

For me (remember that I went through the HA core downgrade so my setup might be messed up, but while someone else replies), after doing 
>Recommended procedure: update XT, then before rebooting update HA to 2025.12.

<img width="254" height="53" alt="Image" src="https://github.com/user-attachments/assets/de8ec281-5740-4247-a80a-5f51c748f238" />

<img width="300" height="auto" alt="Image" src="https://github.com/user-attachments/assets/9aaaea4b-592a-44c5-9b67-78bbe1cfe088" />

The integration doesn't fail to start but all devices are gone, and no logs at all. I also tried re-authenticating

<img width="1078" height="437" alt="Image" src="https://github.com/user-attachments/assets/15747248-a32f-4fbe-8615-99d9c9576f44" />

😅

**Comment by kunickig** [comment]
rb2:
2025-11-28 17:41:15.528 DEBUG (MainThread) [custom_components.xtend_tuya] Xtended Tuya ******@wp.pl 0:00:00.064682 for setup_entity_parsers
2025-11-28 17:41:19.502 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/commonregex.py:5: SyntaxWarning: invalid escape sequence '\:'
  date           = re.compile(u'(?:(?<!\:)(?<!\:\d)[0-3]?\d(?:st|nd|rd|th)?\s+(?:of\s+)?(?:jan\.?|january|feb\.?|february|mar\.?|march|apr\.?|april|may|jun\.?|june|jul\.?|july|aug\.?|august|sep\.?|september|oct\.?|october|nov\.?|november|dec\.?|december)|(?:jan\.?|january|feb\.?|february|mar\.?|march|apr\.?|april|may|jun\.?|june|jul\.?|july|aug\.?|august|sep\.?|september|oct\.?|october|nov\.?|november|dec\.?|december)\s+(?<!\:)(?<!\:\d)[0-3]?\d(?:st|nd|rd|th)?)(?:\,)?\s*(?:\d{4})?|[0-3]?\d[-\./][0-3]?\d[-\./]\d{2,4}', re.IGNORECASE)

and : Rejestrator: tuya_sharing
Źródło: /usr/local/lib/python3.13/site-packages/tuya_sharing/manager.py:138
Pierwsze zdarzenie: 17:41:25 (882 wystąpienia)
Ostatnio zalogowany: 17:53:46

on message error = DeviceListener.update_device() takes 3 positional arguments but 4 were given


I don't see any more errors, but the Tuya accounts don't display any data

**Comment by Bloodiss** [comment]
> can you try with 4.2.6-beta.2 and let me know if you still have the issue?
> 
> Have a nice day, Azerty

My integration also launched without errors. The most devices are present (except for scenarios with Tuya), but all the entities in them are unavailable. There are no errors in the log either.

**Comment by azerty9971** [comment]
I've seen this is the past, disable the XT config then teenable it ;)

**Comment by cloudbr34k84** [comment]
Just tried 4.2.6-beta.2 and integration now loads but now devices anymore lol 😆

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=YnJhZGFwcGxlZ2F0ZTM4QGdtYWlsLmNvbQ==>

On Fri Nov 28, 2025, 09:53 PM GMT, azerty9971 ***@***.***> wrote:
[image]azerty9971 left a comment (azerty9971/xtend_tuya#607) <https://github.com/azerty9971/xtend_tuya/issues/607#issuecomment-3590586226>

**Comment by Bloodiss** [comment]
[azerty9971](https://github.com/azerty9971)
> I've seen this is the past, disable the XT config then teenable it ;)

I did that, but it doesn't help.
As [cloudbr34k84](https://github.com/cloudbr34k84), [kunickig](https://github.com/kunickig) and  [antonio1475](https://github.com/antonio1475) said earlier now devices anymore.
The integration started without errors, but I see this in the log:

`Something is blocking Home Assistant from wrapping up the start up phase. We're going to continue anyway. Please report the following info at https://github.com/home-assistant/core/issues: humidifier, cast.media_player, xtend_tuya.switch, template.sensor, conversation, xiaomi_miot.humidifier, mobile_app.notify, xtend_tuya.event, file, matter.button, number, sql, xtend_tuya, mobile_app.sensor, person, ping.device_tracker, sonoff.alarm_control_panel, onboarding, input_number, xiaomi_miio, tuya.valve, xtend_tuya.binary_sensor, tuya.light, qingping.binary_sensor, xtend_tuya.number, matter.update, xtend_tuya.time, config, repairs, sonoff.climate, xiaomi_miot.number, light, cast, xiaomi_miot.device_tracker, device_automation, hassio.switch, backup.sensor, qingping.sensor, template, alarm_control_panel, tuya.climate, ping, xtend_tuya.cover, utility_meter.sensor, tuya.event, xtend_tuya.alarm_control_panel, utility_meter.select, lovelace, xiaomi_miot.select, matter.water_heater, camera, network, climate, zeroconf, water_heater, mobile_app.binary_sensor, hacs.switch, history, http, matter.lock, system_health, scene, met.weather, diagnostics, mobile_app.device_tracker, tts, weather, my, sonoff.media_player, xiaomi_miot.binary_sensor, xiaomi_miot.fan, systemmonitor.binary_sensor, xiaomi_miot.switch, assist_pipeline, tuya.number, google_translate.tts, button, matter.number, matter.switch, sonoff.fan, sun, mqtt.button, bluetooth_adapters, image_upload, tuya, automation, xiaomi_miot.water_heater, dlna_dmr, mqtt, hardware, event, xiaomi_miio.button, systemmonitor, trace, localtuya.cover, tuya.button, api, backup.event, qingping, hassio.sensor, intent, wake_word, sonoff, xiaomi_miot.sensor, recorder, xiaomi_miot.text, xtend_tuya.lock, matter.event, xiaomi_miio.vacuum, xtend_tuya.vacuum, mqtt.select, xiaomi_miio.binary_sensor, hassio.binary_sensor, persistent_notification, xtend_tuya.select, xiaomi_miot.camera, frontend, sonoff.cover, dhcp, sensor, input_boolean, sonoff.button, cover, logger, sonoff.select, application_credentials, xtend_tuya.climate, go2rtc, tuya.vacuum, snmp.sensor, sonoff.number, tuya.scene, schedule, homeassistant, tuya.fan, xiaomi_miot.climate, energy.sensor, matter.vacuum, tuya.binary_sensor, tuya.siren, webhook, xtend_tuya.sensor, thread, file_upload, xiaomi_miio.sensor, androidtv_remote, hassio, lock, logbook, group, media_source, homeassistant_alerts, google_assistant, mqtt.switch, xiaomi_miot.alarm_control_panel, xtend_tuya.remote, sonoff.sensor, sun.binary_sensor, time, update, input_datetime, binary_sensor, system_log, tuya.cover, vacuum, google_assistant.button, mobile_app, cloud.tts, ssdp, xiaomi_miot.remote, usb, timer, input_select, blueprint, xiaomi_miot.cover, mikrotik.device_tracker, xtend_tuya.camera, ping.binary_sensor, localtuya, hacs, matter, backup, remote, sun.sensor, ffmpeg, systemmonitor.sensor, media_player, mqtt.binary_sensor, matter.valve, mqtt.cover, analytics, sonoff.binary_sensor, sonoff.light, default_config, tuya.humidifier, tuya.sensor, input_text, xiaomi_miot, dlna_dms, matter.cover, xiaomi_miot.light, device_tracker, met, xiaomi_miot.media_player, ping.sensor, xiaomi_miot.vacuum, sql.sensor, localtuya.switch, xiaomi_miot.button, text, bluetooth, labs, dlna_dmr.media_player, matter.select, xtend_tuya.humidifier, localtuya.sensor, stt, script, nodered, tuya.switch, matter.climate, energy, sonoff.switch, matter.sensor, xtend_tuya.siren, mqtt.sensor, auth, cloud, androidtv_remote.media_player, usage_prediction, tuya.alarm_control_panel, xtend_tuya.fan, switch, homeassistant.scene, websocket_api, counter, mikrotik, hassio.update, input_button, matter.fan, valve, matter.light, xtend_tuya.scene, select, sonoff.remote, utility_meter, tuya.camera, tuya.select, zone, tag, search, notify, xtend_tuya.light, fan, xtend_tuya.button, hacs.update, siren, stream, matter.binary_sensor, androidtv_remote.remote, mqtt.update, mqtt.number The system is waiting for tasks: {<Task pending name='Task-466' coro=<AbstractConfig.async_initialize.<locals>.sync_google() running at /usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py:114> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]> cb=[set.remove()]>}`

**Comment by azerty9971** [comment]
Hello,
Can one of you join me on the discord so that we can have a look together at what is happening?

https://discord.gg/3EgfG5sZ4Y

Thanks in advance,
Azerty

**Comment by philspain72** [comment]
let me know if you want me too join

**Comment by scooper1** [comment]
spotted that there was a beta 3 
This beta appears to be working  with entries populated 

Thank you for fixing it  - I will not mark it as completed, I only a tag on with the same problem

**Comment by coltc50** [comment]
+1 updated to Hass b3 and 4.2.6b3 and it's working again. Thank you.

**Comment by Bloodiss** [comment]
4.2.6b3 works. Thank you!

**Comment by azerty9971** [comment]
I'm wondering why I bother to write release notes :p (https://github.com/azerty9971/xtend_tuya/releases)

Yes, that is expected, since there are a lot of changes done on the regular Tuya by Epenet, it's not really possible to have a version compatible with both :).

Thanks for reporting it though ;)

Have a nice day,
Azerty

**Comment by scooper1** [comment]
I am having a problem on restart of ha  get motivation of account expired.  Type of message I don't do any changes but hot then submit button it says issue fixed

**Comment by azerty9971** [comment]
> I am having a problem on restart of ha get motivation of account expired. Type of message I don't do any changes but hot then submit button it says issue fixed

Hello,
Can you please follow this guide and let me know if it helped?
https://github.com/azerty9971/xtend_tuya/blob/main/docs/renew_cloud_credentials.md

Have a nice day,
Azerty

**Comment by scooper1** [comment]
<img width="1406" height="152" alt="Image" src="https://github.com/user-attachments/assets/9e46343f-7ce5-4003-b99e-5fecfa6b381a" />

I checked that the credentials  had not expired   
i the problem happens on every restart, currently on ha 12.0  

i just click on submit, and the problem says fixed - until next restart

**Comment by azerty9971** [comment]
Hello,
Could you come to the discord so that we can have a look at it together?
https://discord.gg/3EgfG5sZ4Y

Thanks in advance,
Azerty

**Comment by scooper1** [comment]
Not available today but may have time tomorrow

**Comment by azerty9971** [comment]
> <img alt="Image" width="1406" height="152" src="https://private-user-images.githubusercontent.com/14822945/522140928-9e46343f-7ce5-4003-b99e-5fecfa6b381a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ4NDIyOTAsIm5iZiI6MTc2NDg0MTk5MCwicGF0aCI6Ii8xNDgyMjk0NS81MjIxNDA5MjgtOWU0NjM0M2YtN2NlNS00MDAzLWI5OWUtNWZlY2ZhNmIzODFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA0VDA5NTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZWQxMWQ0ZDYyYzU2OTFkODgxZDViMzVlMGJlMmM2MDkxMmEzMWQ3NGQ1NzcxNGVmODlkMTcxZjdlYTIzZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xXOlX9ae3i2HWeWqTfQVtBlBi069lbtVtOh7Xxii9Sg">
> 
> I checked that the credentials had not expired i the problem happens on every restart, currently on ha 12.0
> 
> i just click on submit, and the problem says fixed - until next restart

Also, can you open a new issue for this?

This is not related to the 2025.12 update ;).

(The original issue of this thread should be fixed, if not let me know and I'll reopen it).

Have a nice day,
Azerty

**Comment by scooper1** [comment]
This only happened after updating but if no one else has got this problem it maybe a local network issue   let me reboot the network  if I still have problem I will raise a new ticket
Thanks for your rapid response on fixing original issue

**Comment by cloudbr34k84** [comment]
This is still not fixed? Why was it closed? Is no one got this issue anymore?
I still have no devices?

**Comment by scooper1** [comment]
Have you been into hacs and selected redownload to get latest beta version?

**Comment by ColtonYYZ** [comment]
I am so happy with Xtend_tuya!!  So many entities are revealed and usable!!

https://youtu.be/z3SEqzJw9M0
