### ISSUE TITLE
HA 2025.12.0 entities state not updating

### ISSUE THREAD

**Issue by tadeu-lima** [azerty9971/xtend_tuya#624]
After upgrade to HA 2025.12.0 and Xtend Tuya 4.2.6 my gate openers are not updating their state when closed. I have to reload the integration in order to detect the correct state (closed).

**Comment by azerty9971** [comment]
Hello,
This might have been fixed in the beta branch of XT...

Can you try v4.2.7-beta.3 and let me know if you see any changes?

Have a nice day,
Azerty

**Comment by tadeu-lima** [comment]
Just tried it with latest beta, issue still there, now ti opens the gate but does not even detect gate opened need to reload integration.

**Comment by azerty9971** [comment]
can you come to the discord for a second?

https://discord.gg/3EgfG5sZ4Y

Thanks :)

**Comment by tadeu-lima** [comment]
Hi sorry for the late reply.

Now with latest version 4.2.8 beta 1 I can open the gate but the entity still says is closed even after reloading the integration.

**Comment by azerty9971** [comment]
Hello,
This is fixed in the latest beta (v4.2.8-beta.4).

Can you test and confirm that it now works?

Have a nice day,
Azerty

**Comment by tadeu-lima** [comment]
Hi @azerty9971 ,

Unfortunately I can longer provide feedback as I replaced these last two tuya devices I had (gate openers) with Shelly devices.

Therefore I will close this case. Either way thanks for your support and continues development of Xtend Tuya.
