### ISSUE TITLE
LSC Camera - No video

### ISSUE THREAD

**Issue by MorbiasPL** [azerty9971/xtend_tuya#640]
I have issue from updating in November 2025.11. Video is missing.

<img width="582" height="266" alt="Image" src="https://github.com/user-attachments/assets/482532de-96e4-4022-baa9-163f3bce79ad" />

<img width="651" height="1030" alt="Image" src="https://github.com/user-attachments/assets/3f9cd899-5212-4c4b-94fa-a20e0eefe2e4" />

<img width="374" height="753" alt="Image" src="https://github.com/user-attachments/assets/296f43a8-e558-49fb-8bea-73da6707b7bf" />

**Comment by azerty9971** [comment]
Hello,
You can try v4.2.8-beta.3, it should fix this issue :).

I'll release a stable release after some time testing as there are some changes that fix bugs that happen more rarely.

Have a nice day,
Azerty

**Comment by MorbiasPL** [comment]
Thanks, but after installing v4.2.8-beta.3 unfortunately I still don't see video. 

<img width="710" height="1075" alt="Image" src="https://github.com/user-attachments/assets/a84f1479-dbc1-4a56-8d4d-9b335ad59c8b" />

<img width="458" height="949" alt="Image" src="https://github.com/user-attachments/assets/71f676f3-7415-495c-b236-cc7e4da7a301" />

**Comment by azerty9971** [comment]
Hello,
Can you retry with 4.2.8-beta.4?

Have a nice day,
Azerty

**Comment by MorbiasPL** [comment]
Hi, Problem solved :-) - 4.2.8

Thanks!

**Comment by MorbiasPL** [comment]
Hi, Unfortunately cameras is not working as it was few months ago. There is no sound and no Live view after clicking camera 

<img width="580" height="338" alt="Image" src="https://github.com/user-attachments/assets/0b9f2af2-6e54-4a5e-9e8a-0c5f047269ec" />

There is only last refreshed picture

**Comment by MorbiasPL** [comment]
Also log below if it will help:

<img width="1525" height="230" alt="Image" src="https://github.com/user-attachments/assets/e43bef59-6c13-4921-a130-15b1e5530cdc" />

**Comment by azerty9971** [comment]
Hello,
Can you come to the discord so that we can check this together?

https://discord.gg/3EgfG5sZ4Y

Thanks in advance,
Azerty

**Comment by azerty9971** [comment]
Hello,
Can you retry with 4.2.9-beta.4?

Thanks in advance,
Azerty

**Comment by MorbiasPL** [comment]
Te same problem with 4.2.9-beta.4
Sure i can come to Discord. Let me know when.

**Comment by MorbiasPL** [comment]
Video is working now. Just there is no sound.
