### ISSUE TITLE
Thermostat Status Not Updating

### ISSUE THREAD

**Issue by cucupidon** [azerty9971/xtend_tuya#657]
Since a few days/weeks, the xtend_tuya integration is no longer able to display the status of my connected thermostat (heating or off). It constantly shows "unknown" instead.
Expected behavior:
The thermostat status should update in real-time and display either "heating" or "off" as usual.
Current behavior:
The status remains stuck on "unknown" regardless of the actual state of the thermostat.

![Image](https://github.com/user-attachments/assets/d442bafb-8b70-4530-af0b-96a44ac0a3a9)

![Image](https://github.com/user-attachments/assets/58b0c7bc-5f50-4678-8571-46d86c9abf67)

[xtend_tuya-01JG6WWWGD4SW676CMKRTH7S0J-Thermostat radiateur salle à manger -95635ec16f270eee653c6c981cbb6582.json](https://github.com/user-attachments/files/24270793/xtend_tuya-01JG6WWWGD4SW676CMKRTH7S0J-Thermostat.radiateur.salle.a.manger.-95635ec16f270eee653c6c981cbb6582.json)

**Comment by azerty9971** [comment]
Hello,
Can you update to the latest stable version and let me know if you still have the issue? (you should not :)).

Have a nice day et d'avance la bonne année ;),
Azerty

**Comment by cucupidon** [comment]
I just updated to the latest version and unfortunately it didn't fix this bug :-(

Bonne fêtes à toi aussi!

**Comment by ASS35** [comment]
<img width="1099" height="823" alt="Image" src="https://github.com/user-attachments/assets/cf553c08-a039-4414-bee3-988009bffac8" />

I have a similar issue, maybe the screenshot helps to understand? If you tell me what I should try/log I can do so.

**Comment by azerty9971** [comment]
Hello,
This should be fixed in 4.3.0-beta.3.
Please note that this version only supports HA2026.1 and later so either wait for the release of HA2026.1 (this Wednesday) or update your HA to the beta branch.

Have a nice day,
Azerty

**Comment by ASS35** [comment]
Today I updated to Home Assistant 2026.1. Since version 4.3.0 was still on beta 5 about an hour ago, I installed that first, and Xtend started working again in general. However, the specific thermostat issue was still present and remains in the 4.3.0 stable release. 

https://github.com/user-attachments/assets/7319db14-6d2a-4f6a-ab74-8bd421472d68

**Comment by cucupidon** [comment]
I confirm that the bug is still present. The thermostat status is still unknown. If I fiddle with the options, switching from on to off doesn't change anything. However, eco mode does switch the thermostat to eco mode.

https://github.com/user-attachments/assets/55d1db35-08a8-4365-b7dd-1b2e31f8c66f

**Comment by azerty9971** [comment]
Hello,
Can you retry with 4.3.1-beta.5?

This should now be fixed :).

Thanks in advance,
Azerty

**Comment by Itstommy10** [comment]
Ciao @azerty9971, io ho riprovato come hai chiesto tu, la select con l'opzione heating, stop, ecc funziona e mostra il valore attuale della fiammella sul termostato
ma lo stato del termostato rimane sempre in sconosciuto
io avevo provato tempo fa a fare una fix momentanea sull' integrazione ufficiale, https://github.com/Itstommy10/Tuya-custom-integration-climate
@Property
def hvac_mode(self) -> HVACMode | None:
"""Restituisci la modalità hvac."""
# Controllo dello switch fisico (se presente)
switch_status = self._read_wrapper(self._switch_wrapper)
if switch_status is False:
return HVACMode.OFF

    # Se non c'è un wrapper per il modo, ma lo switch è ON
    if self._hvac_mode_wrapper is None:
        if switch_status is True:
            return self.entity_description.switch_only_hvac_mode
        return None

    # Leggiamo lo stato dal cloud
    hvac_status = self._read_wrapper(self._hvac_mode_wrapper)
    
    # Se il cloud dice 'off' o è vuoto (None), ma lo switch non è esplicitamente False
    if hvac_status is None or hvac_status == "off":
        # Se lo switch non esiste o è True, forziamo HEAT per evitare che sparisca
        return HVACMode.HEAT
        
    return TUYA_HVAC_TO_HA.get(hvac_status, HVACMode.HEAT)`
@Property
def hvac_action(self) -> HVACAction | None:
"""Restituisce l'azione HVAC corrente."""
if not self.device.status.get(DPCode.SWITCH, False):
return HVACAction.OFF

    # Usa work_state se disponibile (DP 19)
    if DPCode.WORK_STATE in self.device.status:
        work_state = self.device.status[DPCode.WORK_STATE]
        if work_state == "heating":
            return HVACAction.HEATING
        elif work_state == "cooling":
            return HVACAction.COOLING
        elif work_state == "idle":
            return HVACAction.IDLE

    
    return HVACAction.IDLE

@property
def preset_mode(self) -> str | None:
    """Return preset mode."""
    if self._hvac_mode_wrapper is None:
        return None

    mode = self._read_wrapper(self._hvac_mode_wrapper)
    if mode in TUYA_HVAC_TO_HA:
        return None

    return mode

come posso aiutarti per sistemarlo?

**Comment by cucupidon** [comment]
Hello. I have just updated to the latest beta version and the problem is still present in my home. The thermostat status is still unknown.

![Image](https://github.com/user-attachments/assets/f4a178f2-6e0c-459b-b78c-e97e3eabbd0c)

![Image](https://github.com/user-attachments/assets/2117d179-4165-4811-8e85-5f0a8a07910a)
