### ISSUE TITLE
Smart Lock A1 Ultra 2 recognized but not controllable

### ISSUE THREAD

**Issue by yleduff** [azerty9971/xtend_tuya#673]
I have a A1 Ultra 2 smart lock working through a Wireless Bluetooth gateway.

The lock is recognized in HA, I can see the lock state and I can change the settings but I can't lock nor unlock it.

<img width="348" height="1060" alt="Image" src="https://github.com/user-attachments/assets/627e3542-bd4a-474d-ab0d-c901d1c9654f" />

And the diagnostic
[xtend_tuya-01KB8DVG1K9PFBHR7QEWAVSSRX-A1 Ultra 2-81e1e4e842c7599e88b65d939a1b2132.json](https://github.com/user-attachments/files/24382192/xtend_tuya-01KB8DVG1K9PFBHR7QEWAVSSRX-A1.Ultra.2-81e1e4e842c7599e88b65d939a1b2132.json)

**Comment by grzegorzfus0** [comment]
same problem on my end. Manual lock is working just fine but lock/unlock seems to be either dummy actions (no logs after debug logging enabled) or sillent fail

**Comment by SentinelXS** [comment]
I'm experiencing the same issues with the Smart Lock A1 PRO.
 It started after updating HA to 2025.12.

 I'm using the latest beta version of integration 4.3.1 b5

**Comment by jwhelftx** [comment]
Hi.  I am new to xtend_tuya and having the same problem.  I can manually lock the lock. It won't unlock though.  But I can't unlock/lock it with the toggle at all.  Has anyone found a solution?

**Comment by azerty9971** [comment]
Hello,
Sorry for the delay in answering this issue.

The original issue is caused by the fact that this procedure has not been followed:
https://github.com/azerty9971/xtend_tuya/blob/main/docs/cloud_credentials.md

Maybe you have the same issue?

Can you post a device diagnostic of the lock here? (in HA, go to the device page, then "Download diagnostics" and drag and drop the file here).

Have a nice day,
Azerty

**Comment by jwhelftx** [comment]
I think I followed that procedure.  Also turned on the cloud unlock capability in the project.




________________________________

**Comment by azerty9971** [comment]
Could you please post the device diagnostic so that I can have a look at it?

Thanks in advance,
Azerty

**Comment by jwhelftx** [comment]
[tuya-01KDKEWECMERMFR9YPEHBX5TH8-Smart Lock-KB161-A-aa2bef0e477ddb3f59ea2b90f516d77b-2.json](https://github.com/user-attachments/files/25010984/tuya-01KDKEWECMERMFR9YPEHBX5TH8-Smart.Lock-KB161-A-aa2bef0e477ddb3f59ea2b90f516d77b-2.json)

**Comment by yleduff** [comment]
I think I followed the Cloud Procedure and the Lock Procedure.
My Tuya Project has the correct services with the IoT Core "In Service"

<img width="616" height="737" alt="Image" src="https://github.com/user-attachments/assets/f712a18e-7dfa-4331-a013-9646ce135834" />

The lock and the bluetooth gateway are added.
Shouldn't I put them Controllable ?
<img width="1473" height="326" alt="Image" src="https://github.com/user-attachments/assets/6c4830aa-2f5d-402b-90c1-62688ce8627d" />

Both devices are visible in HA

<img width="387" height="152" alt="Image" src="https://github.com/user-attachments/assets/51442e57-d8f2-42bd-968b-11d2b2d90b4d" />

**Comment by jwhelftx** [comment]
The weirdest thing, is if I use the manual lock feature, it works and shows up on my Tuya app as well as a manual lock.  It only is the Operate Lock function that is not working.    Battery meter also seems to be working in Home Assistant.

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/e0850c44-a4e6-4f34-bcb3-35ef8a9a68ac" />

**Comment by jwhelftx** [comment]
Just following up.  It seems I had a wrong pwd on the credential on the tuya account (not IOT).  Once I corrected this, it seems to be working.  Thank you!

**Comment by HMGOMEZ77** [comment]
any updates on this?

**Comment by yleduff** [comment]
I reinstalled everything and start the procedure from the start but still not working

**Comment by nicolasglg** [comment]
Hey, I ran into the same problem and ended up building a lightweight HACS integration that adds lock/unlock control for Tuya locks and access control devices.

It uses the Tuya Smart Lock Cloud API (ticket-based flow) — the same mechanism the Tuya/Smart Life app uses. Works with categories `mk`, `ms`, `jtmsbh`, `jtmspro` and others. Setup is a 3-step UI config flow with auto-discovery.

**GitHub:** https://github.com/nicolasglg/tuya-smart-lock

Tested on a WiFi access control device (category `mk`). If you try it on your device, let me know how it goes!

**Comment by yleduff** [comment]
> Hey, I ran into the same problem and ended up building a lightweight HACS integration that adds lock/unlock control for Tuya locks and access control devices.
> 
> It uses the Tuya Smart Lock Cloud API (ticket-based flow) — the same mechanism the Tuya/Smart Life app uses. Works with categories `mk`, `ms`, `jtmsbh`, `jtmspro` and others. Setup is a 3-step UI config flow with auto-discovery.
> 
> **GitHub:** https://github.com/nicolasglg/tuya-smart-lock
> 
> Tested on a WiFi access control device (category `mk`). If you try it on your device, let me know how it goes!

I works perfectly. 
Thank you so much

**Comment by nicolasglg** [comment]
Hi @yleduff 

Cool news, please come back to me if any issues. !
 If you want to make my day, buy me a beer 🍺 https://buymeacoffee.com/nicolasglg 

Best
Nico.
